name: ARM64 build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run commands
        uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: aarch64
          distro: bullseye

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          # Install some dependencies in the container.
          install: |
            echo "deb http://deb.debian.org/debian buster-backports main contrib non-free" | tee -a /etc/apt/sources.list.d/backports.list
            apt-get update -q -y
            apt-get install -q -y git golang-1.18 gcc make sed find grep

          # Produce a binary artifact and place it in the mounted volume
          run: |
            git clone git@github.com:bear454/proton-bridge.git
            cd proton-bridge
            make build-nogui
            cp "./cmd/Destop-Bridge/deploy/linux/proton-bridge" "/artifacts/"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: proton-bridge
          path: artifacts/proton-bridge
